{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOv5xaPeA33qqa8SOV8LZZR"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ru31z5R46vym","executionInfo":{"status":"ok","timestamp":1711543233582,"user_tz":180,"elapsed":6305,"user":{"displayName":"Iuridos ps4","userId":"10966233063052844393"}},"outputId":"b1722797-6e0b-4987-9bae-15e822244195"},"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)\n","Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\n"]}],"source":["pip install pandas"]},{"cell_type":"code","source":["import pandas as pd"],"metadata":{"id":"sjzMR4NY7DKY","executionInfo":{"status":"ok","timestamp":1711543280670,"user_tz":180,"elapsed":829,"user":{"displayName":"Iuridos ps4","userId":"10966233063052844393"}}},"execution_count":5,"outputs":[]}]}